#!/usr/bin/env bash
set -euo pipefail

CS_HOME="${CS_HOME:-${HOME}/.claude-switch}"

# ── helpers ───────────────────────────────────────────────────────────────────

_ensure_dir() {
  mkdir -p "${CS_HOME}/providers"
}

_get_default() {
  local config="${CS_HOME}/config.toml"
  if [[ ! -f "$config" ]]; then echo "claude"; return 0; fi
  local line
  line=$(grep -E '^\s*default_provider\s*=' "$config" 2>/dev/null || echo "")
  [[ -z "$line" ]] && { echo "claude"; return 0; }
  echo "$line" | awk -F= '{ sub(/^[[:space:]]+/, "", $2); gsub(/^"|"$/, "", $2); sub(/[[:space:]].*$/, "", $2); print $2 }'
}

_set_default() {
  local provider="$1"
  _ensure_dir

  cat > "${CS_HOME}/config.toml" <<TOML
[core]
default_provider = "${provider}"
TOML

  if [[ "$provider" == "claude" ]]; then
    rm -f "${CS_HOME}/env.zsh"
  else
    cat > "${CS_HOME}/env.zsh" <<SHELL
# Generated by: cs default ${provider}
# Do not edit — run 'cs default <provider>' to change
source "${CS_HOME}/providers/${provider}.zsh"
SHELL
  fi
}

_register_key() {
  local pfile="$1"
  [[ -f "$pfile" ]] || return 0
  command -v zsh &>/dev/null || return 0

  local key
  key=$(zsh -c "source '${pfile}' 2>/dev/null; printf '%s' \"\${ANTHROPIC_AUTH_TOKEN:-}\"" 2>/dev/null || echo "")
  [[ -z "$key" || "$key" == *"your-"*"-api-key-here"* ]] && return 0

  local suffix="${key: -20}"
  for json_path in "${HOME}/.claude.json" "${HOME}/.claude/claude.json"; do
    [[ -f "$json_path" ]] || continue
    grep -q "$suffix" "$json_path" 2>/dev/null && continue
    python3 - "$json_path" "$suffix" <<'PYEOF'
import sys, json
path, suffix = sys.argv[1], sys.argv[2]
with open(path) as f:
    data = json.load(f)
data.setdefault("customApiKeyResponses", {}).setdefault("approved", [])
if suffix not in data["customApiKeyResponses"]["approved"]:
    data["customApiKeyResponses"]["approved"].append(suffix)
with open(path, "w") as f:
    json.dump(data, f, indent=2)
PYEOF
    echo "  [registered key in ${json_path##*/}]"
  done
}

# ── built-in templates ────────────────────────────────────────────────────────

_template_minimax() {
  cat <<'TEMPLATE'
# MiniMax provider
# Get your API key: https://platform.minimaxi.com (mainland) / https://platform.minimax.io (overseas)

export MINIMAX_API_KEY="your-minimax-api-key-here"

export ANTHROPIC_BASE_URL="https://api.minimaxi.com/anthropic"
export ANTHROPIC_AUTH_TOKEN="${MINIMAX_API_KEY}"

export API_TIMEOUT_MS="3000000"
export CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC="1"

export ANTHROPIC_MODEL="MiniMax-M3-highspeed"
export ANTHROPIC_SMALL_FAST_MODEL="MiniMax-M3-highspeed"
export ANTHROPIC_DEFAULT_SONNET_MODEL="MiniMax-M3-highspeed"
export ANTHROPIC_DEFAULT_OPUS_MODEL="MiniMax-M3-highspeed"
export ANTHROPIC_DEFAULT_HAIKU_MODEL="MiniMax-M3-highspeed"

export CLAUDE_SWITCH_PROVIDER="minimax"
TEMPLATE
}

_template_deepseek() {
  cat <<'TEMPLATE'
# DeepSeek provider
# Get your API key: https://platform.deepseek.com

export DEEPSEEK_API_KEY="your-deepseek-api-key-here"

export ANTHROPIC_BASE_URL="https://api.deepseek.com/anthropic"
export ANTHROPIC_AUTH_TOKEN="${DEEPSEEK_API_KEY}"

export CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC="1"
export CLAUDE_CODE_EFFORT_LEVEL="max"

export ANTHROPIC_MODEL="deepseek-v4-pro[1m]"
export ANTHROPIC_DEFAULT_SONNET_MODEL="deepseek-v4-pro[1m]"
export ANTHROPIC_DEFAULT_OPUS_MODEL="deepseek-v4-pro[1m]"
export ANTHROPIC_DEFAULT_HAIKU_MODEL="deepseek-v4-flash[1m]"

export CLAUDE_SWITCH_PROVIDER="deepseek"
TEMPLATE
}

# ── commands ──────────────────────────────────────────────────────────────────

cmd_init_zsh() {
  cat <<'SHELL'
# cs shell integration — generated by "cs init zsh"
# Add to ~/.zshrc: command -v cs &>/dev/null && eval "$(cs init zsh)"

_cs_home="${CS_HOME:-${HOME}/.claude-switch}"

_cs_reset() {
  unset ANTHROPIC_BASE_URL ANTHROPIC_AUTH_TOKEN
  unset ANTHROPIC_MODEL ANTHROPIC_SMALL_FAST_MODEL
  unset ANTHROPIC_DEFAULT_SONNET_MODEL ANTHROPIC_DEFAULT_OPUS_MODEL ANTHROPIC_DEFAULT_HAIKU_MODEL
  unset API_TIMEOUT_MS CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC CLAUDE_CODE_EFFORT_LEVEL
  unset MINIMAX_API_KEY DEEPSEEK_API_KEY
  unset CLAUDE_SWITCH_PROVIDER
}

function cs() {
  local cmd="${1:-}"
  [[ $# -gt 0 ]] && shift
  case "$cmd" in
    use)
      local provider="${1:-claude}"
      _cs_reset
      if [[ "$provider" == "claude" ]]; then
        echo "[cs] switched to claude (OAuth)"
      else
        local pfile="${_cs_home}/providers/${provider}.zsh"
        if [[ -f "$pfile" ]]; then
          source "$pfile"
          echo "[cs] switched to ${provider}"
        else
          echo "[cs] provider not found: ${provider}" >&2
          echo "     run 'cs list' to see installed providers" >&2
          return 1
        fi
      fi
      ;;
    *)
      command cs "$cmd" "$@"
      ;;
  esac
}

[[ -f "${_cs_home}/env.zsh" ]] && source "${_cs_home}/env.zsh"

function _cs_complete() {
  local _h="${_cs_home}"
  case $CURRENT in
    2)
      local -a cmds
      cmds=(
        'use:switch current terminal'
        'default:set global default'
        'add:add a provider'
        'edit:edit provider config'
        'remove:remove a provider'
        'list:list installed providers'
        'status:show current state'
        'init:shell integration'
      )
      _describe 'command' cmds
      ;;
    3)
      case $words[2] in
        use|default|edit|remove)
          local -a providers
          providers=('claude:Claude.ai OAuth')
          for _f in "${_h}/providers/"*.zsh(N); do
            providers+=("${_f:t:r}")
          done
          _describe 'provider' providers
          ;;
        add)
          local -a available
          available=('minimax:MiniMax AI' 'deepseek:DeepSeek' 'claude:Claude.ai OAuth')
          _describe 'provider template' available
          ;;
        init)
          local -a shells
          shells=('zsh:zsh shell integration')
          _describe 'shell' shells
          ;;
      esac
      ;;
  esac
}
(( $+functions[compdef] )) && compdef _cs_complete cs
SHELL
}

cmd_add() {
  local provider="${1:-}"
  if [[ -z "$provider" ]]; then
    echo "usage: cs add <provider>" >&2
    echo "available: minimax, deepseek, claude" >&2
    exit 1
  fi

  if [[ "$provider" == "claude" ]]; then
    cat <<'GUIDE' >&2
[cs] claude uses OAuth — login via Claude Code:
     1. run 'claude'
     2. type /login and follow the browser prompt
     3. exit Claude Code, then run 'cs use claude'
GUIDE
    return 0
  fi

  _ensure_dir

  local pfile="${CS_HOME}/providers/${provider}.zsh"
  if [[ -f "$pfile" ]]; then
    echo "[cs] '${provider}' already exists — use 'cs edit ${provider}' to modify" >&2
    exit 1
  fi

  case "$provider" in
    minimax)  _template_minimax  > "$pfile" ;;
    deepseek) _template_deepseek > "$pfile" ;;
    *)
      echo "[cs] unknown provider: ${provider}" >&2
      echo "     available templates: minimax, deepseek, claude" >&2
      exit 1
      ;;
  esac

  echo "[cs] created ${pfile}"
  "${VISUAL:-${EDITOR:-vi}}" "$pfile"
  _register_key "$pfile"
  echo "[cs] '${provider}' ready"
  echo "     cs default ${provider}   — set as default for new terminals"
  echo "     cs use ${provider}       — switch this terminal now"
}

cmd_edit() {
  local provider="${1:-}"
  if [[ -z "$provider" ]]; then
    echo "usage: cs edit <provider>" >&2
    exit 1
  fi

  if [[ "$provider" == "claude" ]]; then
    echo "[cs] claude has no config to edit (OAuth credentials are managed by 'claude')" >&2
    exit 1
  fi

  local pfile="${CS_HOME}/providers/${provider}.zsh"
  if [[ ! -f "$pfile" ]]; then
    echo "[cs] '${provider}' not found — use 'cs add ${provider}' to create it" >&2
    exit 1
  fi

  "${VISUAL:-${EDITOR:-vi}}" "$pfile"
  _register_key "$pfile"
  echo "[cs] '${provider}' updated"
}

cmd_remove() {
  local provider="${1:-}"
  if [[ -z "$provider" ]]; then
    echo "usage: cs remove <provider>" >&2
    exit 1
  fi

  if [[ "$provider" == "claude" ]]; then
    echo "[cs] 'claude' is built-in and cannot be removed" >&2
    exit 1
  fi

  local pfile="${CS_HOME}/providers/${provider}.zsh"
  if [[ ! -f "$pfile" ]]; then
    echo "[cs] '${provider}' not found" >&2
    exit 1
  fi

  rm "$pfile"
  echo "[cs] removed '${provider}'"

  local current_default
  current_default=$(_get_default)
  if [[ "$current_default" == "$provider" ]]; then
    _set_default "claude"
    echo "[cs] default reset to 'claude'"
  fi
}

cmd_default() {
  if [[ $# -eq 0 ]]; then
    echo "default: $(_get_default)"
    return 0
  fi

  local provider="$1"
  if [[ "$provider" != "claude" ]]; then
    local pfile="${CS_HOME}/providers/${provider}.zsh"
    if [[ ! -f "$pfile" ]]; then
      echo "[cs] '${provider}' not found — use 'cs add ${provider}' first" >&2
      exit 1
    fi
  fi

  _set_default "$provider"
  echo "[cs] default → ${provider} (takes effect in new terminals)"
}

cmd_list() {
  local current_default
  current_default=$(_get_default)
  echo "Providers:"
  local marker
  marker="$([ "$current_default" = "claude" ] && echo " ← default" || echo "")"
  printf "  %-14s Claude.ai (OAuth)%s\n" "claude" "$marker"
  for f in "${CS_HOME}/providers/"*.zsh; do
    [[ -f "$f" ]] || continue
    local name="${f##*/}"
    name="${name%.zsh}"
    marker="$([ "$current_default" = "$name" ] && echo " ← default" || echo "")"
    printf "  %-14s %s\n" "$name" "$marker"
  done
}

cmd_status() {
  local current_provider
  if [[ -n "${ANTHROPIC_AUTH_TOKEN:-}" ]]; then
    current_provider="${CLAUDE_SWITCH_PROVIDER:-unknown}"
  else
    current_provider="claude"
  fi

  printf "%-20s %s\n" "Current terminal:"  "$current_provider"
  printf "%-20s %s\n" "Global default:"    "$(_get_default)"
  printf "%-20s %s\n" "Base URL:"          "${ANTHROPIC_BASE_URL:-(unset)}"
  printf "%-20s %s\n" "Auth token:"        "$([[ -n "${ANTHROPIC_AUTH_TOKEN:-}" ]] && echo 'set (hidden)' || echo 'unset')"
  printf "%-20s %s\n" "Model:"             "${ANTHROPIC_MODEL:-(unset)}"
  printf "%-20s %s\n" "CS_HOME:"           "${CS_HOME}"
}

cmd_help() {
  cat <<'HELP'
cs — Claude Code provider switcher

Usage:
  cs init zsh           print shell integration code (add to .zshrc)
  cs add <provider>     add a provider: minimax | deepseek | claude
  cs edit <provider>    edit provider config in $EDITOR
  cs remove <provider>  remove a provider
  cs use <provider>     switch current terminal  (requires shell integration)
  cs default [prov]     get or set global default provider
  cs list               list installed providers
  cs status             show current state

Shell integration (add to ~/.zshrc):
  command -v cs &>/dev/null && eval "$(cs init zsh)"

Providers are stored in: ~/.claude-switch/providers/
HELP
}

# ── dispatch ──────────────────────────────────────────────────────────────────

cmd="${1:-}"
[[ $# -gt 0 ]] && shift

case "$cmd" in
  init)
    sub="${1:-}"
    case "$sub" in
      zsh) cmd_init_zsh ;;
      *)   echo "[cs] usage: cs init zsh" >&2; exit 1 ;;
    esac
    ;;
  add)     cmd_add     "$@" ;;
  edit)    cmd_edit    "$@" ;;
  remove)  cmd_remove  "$@" ;;
  default) cmd_default "$@" ;;
  list)    cmd_list ;;
  status)  cmd_status ;;
  use)
    echo "[cs] 'cs use' requires shell integration" >&2
    echo "     add to ~/.zshrc: command -v cs &>/dev/null && eval \"\$(cs init zsh)\"" >&2
    exit 1
    ;;
  "")  cmd_help ;;
  *)
    echo "[cs] unknown command: ${cmd}" >&2
    echo "     run 'cs' for help" >&2
    exit 1
    ;;
esac
